---
version: "3"
services:
  ballotserver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: ./docker/env_file
    volumes:
      - storage:/app/app/data/storage/
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - AUDIT_WRITE
    restart: unless-stopped
  revproxy:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 443:443
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - AUDIT_WRITE
      - CHOWN
      - SETGID
      - SETUID

volumes:
  storage: