---
version: "3"
services:
  ballotserver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: ./docker/env_file
    volumes:
      - ./data/storage/:/app/data/storage/
    ports:
      - 80:80
