---
version: "3"
services:
  ballotserver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: ./docker/env_file
    volumes:
      - ./app/data/storage/:/app/data/storage/
  revproxy:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 443:443
